# Test Matrix: DirectIO Backend Configuration
model:
  name: "directio_backend_test"
  
framework: "pytorch"

workflow:
  generate_data: true
  train: true
  checkpoint: true

dataset:
  data_folder: "direct:///mnt/vast1/dl_driver_test_matrix_directio"
  format: "npz"
  num_files_train: 8
  record_length_bytes: 1024
  num_samples_per_file: 10

reader:
  batch_size: 4
  prefetch: 2
  shuffle: true
  read_threads: 2
  seed: 42

checkpoint:
  enabled: true
  steps_between_checkpoints: 3
  compression: "zstd"
  compression_level: 3