#!/bin/bash
# Manual checkpoint testing script for dl-driver
# Tests checkpoint save/load/reload functionality with various storage backends
#
# Usage:
#   ./manual_checkpoint_test.sh file    # Test with local file:// storage
#   ./manual_checkpoint_test.sh s3      # Test with AWS S3 (requires credentials)
#   ./manual_checkpoint_test.sh azure   # Test with Azure Blob (requires credentials)
#   ./manual_checkpoint_test.sh gcs     # Test with Google Cloud Storage (requires credentials)

set -e  # Exit on error

BACKEND=${1:-file}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DL_DRIVER="${SCRIPT_DIR}/../target/release/dl-driver"
TEST_DIR="/mnt/test/dl-driver-checkpoint-test-$(date +%s)"
CONFIG_FILE="${TEST_DIR}/test_config.yaml"

echo "=========================================="
echo "dl-driver Checkpoint Test"
echo "Backend: ${BACKEND}"
echo "Test directory: ${TEST_DIR}"
echo "=========================================="

# Create test directory structure
mkdir -p "${TEST_DIR}/data"
mkdir -p "${TEST_DIR}/checkpoints_save"
mkdir -p "${TEST_DIR}/checkpoints_reload"

# Generate some test data files
echo "Generating test data..."
for i in {0..9}; do
    dd if=/dev/zero of="${TEST_DIR}/data/sample_$(printf '%04d' $i).npz" bs=1K count=1 2>/dev/null
done
echo "✓ Generated 10 test files (1KB each)"

# Determine checkpoint URI based on backend
case "${BACKEND}" in
    file)
        CHECKPOINT_URI="file://${TEST_DIR}/checkpoints_save"
        CHECKPOINT_RELOAD_URI="file://${TEST_DIR}/checkpoints_reload"
        echo "Using local filesystem storage"
        ;;
    s3)
        if [ -z "${S3_TEST_BUCKET}" ]; then
            echo "ERROR: S3_TEST_BUCKET environment variable not set"
            echo "Set it with: export S3_TEST_BUCKET=your-bucket-name"
            exit 1
        fi
        TEST_PREFIX="dl-driver-manual-test-$(date +%s)"
        CHECKPOINT_URI="s3://${S3_TEST_BUCKET}/${TEST_PREFIX}/checkpoints_save"
        CHECKPOINT_RELOAD_URI="s3://${S3_TEST_BUCKET}/${TEST_PREFIX}/checkpoints_reload"
        echo "Using S3 bucket: ${S3_TEST_BUCKET}"
        echo "Test prefix: ${TEST_PREFIX}"
        ;;
    azure)
        if [ -z "${AZURE_STORAGE_ACCOUNT_NAME}" ] || [ -z "${AZURE_TEST_CONTAINER}" ]; then
            echo "ERROR: Azure environment variables not set"
            echo "Required: AZURE_STORAGE_ACCOUNT_NAME, AZURE_STORAGE_ACCOUNT_KEY, AZURE_TEST_CONTAINER"
            exit 1
        fi
        TEST_PREFIX="dl-driver-manual-test-$(date +%s)"
        CHECKPOINT_URI="az://${AZURE_STORAGE_ACCOUNT_NAME}/${AZURE_TEST_CONTAINER}/${TEST_PREFIX}/checkpoints_save"
        CHECKPOINT_RELOAD_URI="az://${AZURE_STORAGE_ACCOUNT_NAME}/${AZURE_TEST_CONTAINER}/${TEST_PREFIX}/checkpoints_reload"
        echo "Using Azure account: ${AZURE_STORAGE_ACCOUNT_NAME}"
        echo "Container: ${AZURE_TEST_CONTAINER}"
        echo "Test prefix: ${TEST_PREFIX}"
        ;;
    gcs)
        if [ -z "${GCS_TEST_BUCKET}" ]; then
            echo "ERROR: GCS_TEST_BUCKET environment variable not set"
            echo "Set it with: export GCS_TEST_BUCKET=your-bucket-name"
            exit 1
        fi
        TEST_PREFIX="dl-driver-manual-test-$(date +%s)"
        CHECKPOINT_URI="gs://${GCS_TEST_BUCKET}/${TEST_PREFIX}/checkpoints_save"
        CHECKPOINT_RELOAD_URI="gs://${GCS_TEST_BUCKET}/${TEST_PREFIX}/checkpoints_reload"
        echo "Using GCS bucket: ${GCS_TEST_BUCKET}"
        echo "Test prefix: ${TEST_PREFIX}"
        ;;
    *)
        echo "ERROR: Unknown backend '${BACKEND}'"
        echo "Supported: file, s3, azure, gcs"
        exit 1
        ;;
esac

# Create YAML config for checkpoint testing
cat > "${CONFIG_FILE}" <<EOF
# dl-driver checkpoint test configuration
# Generated by manual_checkpoint_test.sh

model:
  name: "manual_checkpoint_test"

framework: "pytorch"

# Dataset configuration
dataset:
  data_folder: file://${TEST_DIR}/data
  format: npz
  num_files_train: 10
  num_samples_per_file: 1
  record_length_bytes: 1024

# Checkpoint configuration - save every 2 steps
checkpointing:
  checkpoint_folder: ${CHECKPOINT_URI}
  steps_between_checkpoints: 2

# Reader configuration
reader:
  data_loader: pytorch
  read_threads: 1
  batch_size: 2
  prefetch: 1
  shuffle: false
  seed: 42

# Training workflow
workflow:
  train: true
  generate_data: false
  checkpoint: true

# Training configuration
train:
  epochs: 2
  computation_time: 0.0
  
# Logging
enable_profiling: false
EOF

echo ""
echo "=========================================="
echo "Phase 1: Training with Checkpoint Save"
echo "=========================================="
echo "Config: ${CONFIG_FILE}"
echo "Checkpoint URI: ${CHECKPOINT_URI}"
echo ""

# Check if dl-driver binary exists
if [ ! -f "${DL_DRIVER}" ]; then
    echo "ERROR: dl-driver binary not found at ${DL_DRIVER}"
    echo "Build it first with: cargo build --release"
    exit 1
fi

# Validate config with --dry-run
echo "Validating config with --dry-run..."
echo "Running: ${DL_DRIVER} -v run --config ${CONFIG_FILE} --dry-run"
if ! "${DL_DRIVER}" -v run --config "${CONFIG_FILE}" --dry-run; then
    echo ""
    echo "ERROR: Config validation failed!"
    echo "Check the config file at: ${CONFIG_FILE}"
    exit 1
fi
echo "✓ Config validation passed"
echo ""

# Run training phase with checkpoint saving (with 10 second timeout for safety)
echo "Running: timeout 10 ${DL_DRIVER} -v run --config ${CONFIG_FILE}"
if ! timeout 10 "${DL_DRIVER}" -v run --config "${CONFIG_FILE}"; then
    EXIT_CODE=$?
    if [ ${EXIT_CODE} -eq 124 ]; then
        echo ""
        echo "ERROR: Training phase timed out after 10 seconds!"
        echo "This may indicate a hang or performance issue."
    else
        echo ""
        echo "ERROR: Training phase failed with exit code ${EXIT_CODE}"
    fi
    exit ${EXIT_CODE}
fi

echo ""
echo "✓ Training phase complete"
echo ""

# Find the most recent checkpoint
echo "=========================================="
echo "Finding Saved Checkpoints"
echo "=========================================="

case "${BACKEND}" in
    file)
        CHECKPOINT_FILES=$(find "${TEST_DIR}/checkpoints_save" -name "*.ckpt" -type f 2>/dev/null || true)
        if [ -z "${CHECKPOINT_FILES}" ]; then
            echo "ERROR: No checkpoint files found!"
            exit 1
        fi
        LATEST_CHECKPOINT=$(echo "${CHECKPOINT_FILES}" | head -1)
        echo "Found checkpoint: ${LATEST_CHECKPOINT}"
        CHECKPOINT_COUNT=$(echo "${CHECKPOINT_FILES}" | wc -l)
        echo "Total checkpoints: ${CHECKPOINT_COUNT}"
        ;;
    *)
        echo "Checkpoint listing for ${BACKEND} requires manual verification"
        echo "Check your cloud storage console to verify checkpoints were created"
        echo "Expected location: ${CHECKPOINT_URI}"
        read -p "Press Enter to continue with reload test, or Ctrl-C to abort..."
        ;;
esac

echo ""
echo "=========================================="
echo "Phase 2: Training with Checkpoint Reload"
echo "=========================================="

# Update config for reload phase
cat > "${CONFIG_FILE}" <<EOF
# dl-driver checkpoint reload test configuration
# Generated by manual_checkpoint_test.sh - Phase 2

model:
  name: "manual_checkpoint_reload_test"

framework: "pytorch"

# Dataset configuration
dataset:
  data_folder: file://${TEST_DIR}/data
  format: npz
  num_files_train: 10
  num_samples_per_file: 1
  record_length_bytes: 1024

# Checkpoint configuration - reload from previous run, save to new location
checkpointing:
  checkpoint_folder: ${CHECKPOINT_RELOAD_URI}
  steps_between_checkpoints: 2
  # Note: checkpoint_reload_path would go here when implemented

# Reader configuration
reader:
  data_loader: pytorch
  read_threads: 1
  batch_size: 2
  prefetch: 1
  shuffle: false
  seed: 42

# Training workflow
workflow:
  train: true
  generate_data: false
  checkpoint: true

# Training configuration
train:
  epochs: 2
  computation_time: 0.0
  
# Logging
enable_profiling: false
EOF

echo "Config: ${CONFIG_FILE}"
echo "New checkpoint URI: ${CHECKPOINT_RELOAD_URI}"
echo ""
echo "Note: Currently testing checkpoint save/load verification."
echo "      Full reload functionality (resuming from checkpoint) is in v0.8.4"
echo ""

# Validate reload config with --dry-run
echo "Validating reload config with --dry-run..."
if ! "${DL_DRIVER}" -v run --config "${CONFIG_FILE}" --dry-run; then
    echo ""
    echo "ERROR: Reload config validation failed!"
    exit 1
fi
echo "✓ Reload config validation passed"
echo ""

# Run second training phase (would reload checkpoint when implemented)
echo "Running: timeout 10 ${DL_DRIVER} -v run --config ${CONFIG_FILE}"
if ! timeout 10 "${DL_DRIVER}" -v run --config "${CONFIG_FILE}"; then
    EXIT_CODE=$?
    if [ ${EXIT_CODE} -eq 124 ]; then
        echo ""
        echo "ERROR: Reload training phase timed out after 10 seconds!"
    else
        echo ""
        echo "ERROR: Reload training phase failed with exit code ${EXIT_CODE}"
    fi
    exit ${EXIT_CODE}
fi

echo ""
echo "✓ Reload training phase complete"
echo ""

echo "=========================================="
echo "Test Summary"
echo "=========================================="
echo "Backend: ${BACKEND}"
echo "Phase 1 checkpoints: ${CHECKPOINT_URI}"
echo "Phase 2 checkpoints: ${CHECKPOINT_RELOAD_URI}"
echo ""

case "${BACKEND}" in
    file)
        SAVE_COUNT=$(find "${TEST_DIR}/checkpoints_save" -name "*.ckpt" -type f 2>/dev/null | wc -l)
        RELOAD_COUNT=$(find "${TEST_DIR}/checkpoints_reload" -name "*.ckpt" -type f 2>/dev/null | wc -l)
        echo "Checkpoints created in Phase 1: ${SAVE_COUNT}"
        echo "Checkpoints created in Phase 2: ${RELOAD_COUNT}"
        
        if [ "${SAVE_COUNT}" -gt 0 ] && [ "${RELOAD_COUNT}" -gt 0 ]; then
            echo ""
            echo "✅ SUCCESS: Checkpoints created in both phases"
        else
            echo ""
            echo "❌ FAILURE: Missing checkpoints"
            exit 1
        fi
        ;;
    *)
        echo "Verify checkpoints in your cloud storage:"
        echo "  Phase 1: ${CHECKPOINT_URI}"
        echo "  Phase 2: ${CHECKPOINT_RELOAD_URI}"
        ;;
esac

echo ""
echo "Test directory: ${TEST_DIR}"
echo "To clean up: rm -rf ${TEST_DIR}"
echo ""
echo "=========================================="
echo "✅ Manual checkpoint test complete!"
echo "=========================================="
