[package]
name    = "real_dlio"          # ← the binary you will run
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow      = "1.0"
clap        = { version = "4.5", features = ["derive"] }
serde_yaml  = "0.9"
real_dlio_core = { path = "../core" }   # ← library dependency

